// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DeployOffice(arg1:string):Promise<void>;

export function DeployPrinters(arg1:string):Promise<void>;

export function DeploySentinel(arg1:string):Promise<void>;

export function DeploySoftware(arg1:Array<string>):Promise<void>;

export function DeploySophos(arg1:string):Promise<void>;

export function DeployToTargets(arg1:Array<string>,arg2:backend.DeployFunc):Promise<void>;

export function GetComputers():Promise<Array<backend.Computer>>;

export function HostName():Promise<string>;
