// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployOffice(arg1) {
  return window['go']['backend']['App']['DeployOffice'](arg1);
}

export function DeployPrinters(arg1) {
  return window['go']['backend']['App']['DeployPrinters'](arg1);
}

export function DeploySentinel(arg1) {
  return window['go']['backend']['App']['DeploySentinel'](arg1);
}

export function DeploySoftware(arg1) {
  return window['go']['backend']['App']['DeploySoftware'](arg1);
}

export function DeploySophos(arg1) {
  return window['go']['backend']['App']['DeploySophos'](arg1);
}

export function DeployToTargets(arg1, arg2) {
  return window['go']['backend']['App']['DeployToTargets'](arg1, arg2);
}

export function GetComputers() {
  return window['go']['backend']['App']['GetComputers']();
}

export function HostName() {
  return window['go']['backend']['App']['HostName']();
}
